export const ROUTES = {
  HOME: "/",
  SHOP: "/products",
  PRODUCTSINGLE: "products/:slug",
  CATEGORY: "category",
  CATEGORYSINGLE: "category/:slug",
  BLOG: "blog",
  BLOGSINGLE: "blog/:slug",
  CONTACT: "contact",
  REGISTER: "/register",
  LOGIN: "/login",
  RESETPASSWORD: "/forgotPassword",
  DASHBOARD: "/dashboard",
  USER: "/user",
  SEARCH: "/search",
  WISHLIST: "/wishlist",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER: "/order",
  NOTFOUND: "*",
};
